/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package clienteGUI;

import conexion.conexion;
import java.awt.Color;
import java.awt.Desktop;
import java.io.File;
import java.io.FileNotFoundException;
import java.io.FileOutputStream;
import java.io.IOException;
import javax.swing.plaf.InternalFrameUI;
import javax.swing.plaf.basic.BasicInternalFrameUI;
import javax.swing.table.TableRowSorter;
import javax.swing.table.DefaultTableModel;
import java.sql.PreparedStatement;
import java.sql.ResultSet;
import java.sql.SQLException;
import java.text.SimpleDateFormat;
import java.util.Date;
import javax.swing.JFileChooser;
import javax.swing.JOptionPane;
import org.apache.poi.hssf.usermodel.HSSFWorkbook;
import org.apache.poi.ss.usermodel.BorderStyle;
import org.apache.poi.ss.usermodel.Cell;
import org.apache.poi.ss.usermodel.CellStyle;
import org.apache.poi.ss.usermodel.FillPatternType;
import org.apache.poi.ss.usermodel.Font;
import org.apache.poi.ss.usermodel.Header;
import org.apache.poi.ss.usermodel.IndexedColors;
import org.apache.poi.ss.usermodel.Row;
import org.apache.poi.ss.usermodel.Sheet;
import org.apache.poi.ss.usermodel.Workbook;
import org.apache.poi.xssf.usermodel.XSSFSheet;
import org.apache.poi.xssf.usermodel.XSSFWorkbook;

/**
 *
 * @author danie
 */
public class InformePackComunas extends javax.swing.JInternalFrame {

    DefaultTableModel dtmBanco;
    TableRowSorter trs;
    DefaultTableModel modeloDespachos;
    int nroPedido = 0;
    conexion con = new conexion();

    public InformePackComunas() throws Exception {
        initComponents();

        this.getContentPane().setBackground(new Color(72, 70, 92));
        modeloDespachos = new DefaultTableModel();

        modeloDespachos.addColumn("Comuna");
        modeloDespachos.addColumn("Pack");
        modeloDespachos.addColumn("Cantidad");
        modeloDespachos.addColumn("Total");
        this.tblDespachos.setModel(modeloDespachos);
        comunas();

    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")

//    private void listarPendientes() {
//
//        try {
//
//            con.connections();
//            PreparedStatement pstm = con.conexion.prepareStatement("select * from venta,cliente,pack where EST_ID_ESTADO  ='" + 2 + "' and"
//                    + " venta.CLI_ID_CLIENTE=cliente.id_cliente and venta.PCK_ID_PACK=pack.id_pack ");
//            ResultSet respuesta1 = pstm.executeQuery();
//
//            while (respuesta1.next()) {
//
////                if (respuesta1.getInt("EST_ID_ESTADO") == 1) {
//                Object[] dato = {
//                    respuesta1.getInt("vta_id_venta"),
//                    respuesta1.getString("VTA_FECHA_ENTREGA"),
//                    respuesta1.getString("cli_nombre"),
//                    respuesta1.getString("cli_telefono"),
//                    respuesta1.getString("VTA_TOTAL"),
//                    respuesta1.getString("pack_nombre")};
//
//                modeloDespachos.addRow(dato);
////                }
//
//            }
//
//        } catch (Exception e) {
//            System.out.println("no se listo pendientes por error : " + e);
//        }
//
//    }
    @Override
    public void setUI(InternalFrameUI ui) {
        super.setUI(ui);

        BasicInternalFrameUI frameUI = (BasicInternalFrameUI) getUI();
        if (frameUI != null) {
            frameUI.setNorthPane(null);
        }
    }

    void comunas() {

        try {
            con.connections();
            PreparedStatement pstm = con.conexion.prepareStatement("select * from comuna");
            ResultSet respuesta = pstm.executeQuery();

            while (respuesta.next()) {

                cmbComuna.addItem(respuesta.getString("com_nombre"));
            }

        } catch (SQLException e) {
        }

    }


    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jLabel7 = new javax.swing.JLabel();
        jScrollPane2 = new javax.swing.JScrollPane();
        tblDespachos = new javax.swing.JTable();
        InformeComunas1 = new com.toedter.calendar.JDateChooser();
        BuscarInformeComuna = new javax.swing.JButton();
        InformeComunas2 = new com.toedter.calendar.JDateChooser();
        cmbComuna = new javax.swing.JComboBox<>();
        jLabel8 = new javax.swing.JLabel();
        txtTotal = new javax.swing.JTextField();
        jLabel10 = new javax.swing.JLabel();
        jButton2 = new javax.swing.JButton();
        jLabel9 = new javax.swing.JLabel();
        jLabel11 = new javax.swing.JLabel();

        setBackground(new java.awt.Color(102, 102, 255));
        setBorder(javax.swing.BorderFactory.createMatteBorder(3, 3, 3, 3, new java.awt.Color(0, 0, 0)));
        setAutoscrolls(true);
        setCursor(new java.awt.Cursor(java.awt.Cursor.DEFAULT_CURSOR));
        setEnabled(false);
        setFocusCycleRoot(false);
        setFocusable(false);
        setPreferredSize(new java.awt.Dimension(1006, 611));
        setRequestFocusEnabled(false);
        setVerifyInputWhenFocusTarget(false);
        setVisible(true);

        jLabel7.setFont(new java.awt.Font("Verdana", 1, 18)); // NOI18N
        jLabel7.setForeground(new java.awt.Color(255, 255, 255));
        jLabel7.setText("Pack Vendidos por Comuna");

        tblDespachos.setBorder(new javax.swing.border.SoftBevelBorder(javax.swing.border.BevelBorder.RAISED));
        tblDespachos.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null}
            },
            new String [] {
                "Title 1", "Title 2", "Title 3", "Title 4"
            }
        ));
        tblDespachos.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                tblDespachosMouseClicked(evt);
            }
        });
        jScrollPane2.setViewportView(tblDespachos);

        InformeComunas1.setFocusable(false);
        InformeComunas1.addContainerListener(new java.awt.event.ContainerAdapter() {
            public void componentRemoved(java.awt.event.ContainerEvent evt) {
                InformeComunas1ComponentRemoved(evt);
            }
        });
        InformeComunas1.addFocusListener(new java.awt.event.FocusAdapter() {
            public void focusLost(java.awt.event.FocusEvent evt) {
                InformeComunas1FocusLost(evt);
            }
        });

        BuscarInformeComuna.setIcon(new javax.swing.ImageIcon(getClass().getResource("/recurso/icons/buscar.png"))); // NOI18N
        BuscarInformeComuna.setText("Buscar");
        BuscarInformeComuna.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                BuscarInformeComunaActionPerformed(evt);
            }
        });

        InformeComunas2.setFocusable(false);
        InformeComunas2.addContainerListener(new java.awt.event.ContainerAdapter() {
            public void componentRemoved(java.awt.event.ContainerEvent evt) {
                InformeComunas2ComponentRemoved(evt);
            }
        });
        InformeComunas2.addFocusListener(new java.awt.event.FocusAdapter() {
            public void focusLost(java.awt.event.FocusEvent evt) {
                InformeComunas2FocusLost(evt);
            }
        });

        cmbComuna.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "Seleccione Comunas" }));

        jLabel8.setFont(new java.awt.Font("Verdana", 1, 14)); // NOI18N
        jLabel8.setForeground(new java.awt.Color(255, 255, 255));
        jLabel8.setText("Comunas");

        jLabel10.setFont(new java.awt.Font("Verdana", 1, 14)); // NOI18N
        jLabel10.setForeground(new java.awt.Color(255, 255, 255));
        jLabel10.setText("Total");

        jButton2.setIcon(new javax.swing.ImageIcon(getClass().getResource("/recurso/icons/excel-icon.png"))); // NOI18N
        jButton2.setText("Exportar");
        jButton2.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton2ActionPerformed(evt);
            }
        });

        jLabel9.setFont(new java.awt.Font("Verdana", 1, 14)); // NOI18N
        jLabel9.setForeground(new java.awt.Color(255, 255, 255));
        jLabel9.setText("Desde");

        jLabel11.setFont(new java.awt.Font("Verdana", 1, 14)); // NOI18N
        jLabel11.setForeground(new java.awt.Color(255, 255, 255));
        jLabel11.setText("Hasta");

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGap(21, 21, 21)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jLabel7, javax.swing.GroupLayout.PREFERRED_SIZE, 331, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addGroup(layout.createSequentialGroup()
                        .addComponent(jLabel11)
                        .addGap(18, 18, 18)
                        .addComponent(InformeComunas2, javax.swing.GroupLayout.PREFERRED_SIZE, 215, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(layout.createSequentialGroup()
                        .addGap(680, 680, 680)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                            .addComponent(jButton2)
                            .addGroup(layout.createSequentialGroup()
                                .addComponent(jLabel10, javax.swing.GroupLayout.PREFERRED_SIZE, 51, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addComponent(txtTotal, javax.swing.GroupLayout.PREFERRED_SIZE, 170, javax.swing.GroupLayout.PREFERRED_SIZE))))
                    .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING, false)
                        .addComponent(BuscarInformeComuna, javax.swing.GroupLayout.PREFERRED_SIZE, 129, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addComponent(jScrollPane2, javax.swing.GroupLayout.PREFERRED_SIZE, 915, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGroup(layout.createSequentialGroup()
                            .addComponent(jLabel9)
                            .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                            .addComponent(InformeComunas1, javax.swing.GroupLayout.PREFERRED_SIZE, 215, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                            .addComponent(jLabel8)
                            .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                            .addComponent(cmbComuna, javax.swing.GroupLayout.PREFERRED_SIZE, 214, javax.swing.GroupLayout.PREFERRED_SIZE))))
                .addContainerGap(64, Short.MAX_VALUE))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGap(39, 39, 39)
                .addComponent(jLabel7)
                .addGap(26, 26, 26)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(jLabel8)
                            .addComponent(cmbComuna, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 53, Short.MAX_VALUE))
                    .addGroup(layout.createSequentialGroup()
                        .addGap(0, 0, Short.MAX_VALUE)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(InformeComunas1, javax.swing.GroupLayout.PREFERRED_SIZE, 30, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(jLabel9))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(InformeComunas2, javax.swing.GroupLayout.PREFERRED_SIZE, 30, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(jLabel11)
                            .addComponent(BuscarInformeComuna, javax.swing.GroupLayout.PREFERRED_SIZE, 30, javax.swing.GroupLayout.PREFERRED_SIZE))))
                .addGap(13, 13, 13)
                .addComponent(jScrollPane2, javax.swing.GroupLayout.PREFERRED_SIZE, 265, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(18, 18, 18)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(txtTotal, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabel10))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(jButton2)
                .addGap(42, 42, 42))
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void tblDespachosMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_tblDespachosMouseClicked

    }//GEN-LAST:event_tblDespachosMouseClicked

    private void InformeComunas1FocusLost(java.awt.event.FocusEvent evt) {//GEN-FIRST:event_InformeComunas1FocusLost


    }//GEN-LAST:event_InformeComunas1FocusLost

    private void BuscarInformeComunaActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_BuscarInformeComunaActionPerformed

        modeloDespachos.setRowCount(0);
int total = 0, contador = 0;
        Date date = InformeComunas1.getDate();
        SimpleDateFormat sdf = new SimpleDateFormat("yyyy/MM/dd");
        String fechaVenta1 = (String.valueOf(sdf.format(date)));
        Date date1 = InformeComunas2.getDate();
        String fechaVenta2 = (String.valueOf(sdf.format(date1)));

        System.out.println(fechaVenta1);

        System.out.println("hola despachos");

        try {

            con.connections();

            String sql = ("SELECT C.pack_nombre,k.com_nombre,v.vta_cantidad, COUNT(*)\n"
                    + "CONTADOR FROM venta V \n"
                    + "INNER JOIN pack C ON C.id_pack=V.PCK_ID_PACK INNER JOIN comuna k ON v.COM_ID_COMUNA=k.id_comuna\n"
                    + "WHERE v.VTA_FECHA_ENTREGA BETWEEN '" + fechaVenta1 + "' AND '" + fechaVenta2 + "' and k.com_nombre='" + cmbComuna.getSelectedItem() + "'\n"
                    + "GROUP BY C.pack_nombre,k.com_nombre\n"
                    + "ORDER BY CONTADOR");
            PreparedStatement pstm = con.conexion.prepareStatement(sql);
            ResultSet respuesta1 = pstm.executeQuery();

            while (respuesta1.next()) {

//                if (respuesta1.getInt("EST_ID_ESTADO") == 1) {
                Object[] dato = {
                    respuesta1.getString("pack_nombre"),
                    respuesta1.getString("com_nombre"),
                    respuesta1.getString("CONTADOR"),
                    (respuesta1.getInt("CONTADOR")) * respuesta1.getInt("VTA_CANTIDAD")};

                modeloDespachos.addRow(dato);
                
                
                total = (respuesta1.getInt("CONTADOR")) * respuesta1.getInt("VTA_CANTIDAD");

                contador = total + contador;


            }
            
            txtTotal.setText("$"+String.valueOf(contador));

        } catch (Exception e) {
            System.out.println("no se listo pendientes por error : " + e);
        }
    }//GEN-LAST:event_BuscarInformeComunaActionPerformed

    private void InformeComunas1ComponentRemoved(java.awt.event.ContainerEvent evt) {//GEN-FIRST:event_InformeComunas1ComponentRemoved

    }//GEN-LAST:event_InformeComunas1ComponentRemoved

    private void InformeComunas2ComponentRemoved(java.awt.event.ContainerEvent evt) {//GEN-FIRST:event_InformeComunas2ComponentRemoved
        // TODO add your handling code here:
    }//GEN-LAST:event_InformeComunas2ComponentRemoved

    private void InformeComunas2FocusLost(java.awt.event.FocusEvent evt) {//GEN-FIRST:event_InformeComunas2FocusLost
        // TODO add your handling code here:
    }//GEN-LAST:event_InformeComunas2FocusLost

    private void jButton2ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton2ActionPerformed

        try {

            JFileChooser jFileChooser = new JFileChooser();
            jFileChooser.showSaveDialog(this);
            File saveFile = jFileChooser.getSelectedFile();

            if (saveFile != null) {
                saveFile = new File(saveFile.toString() + ".xlsx");
                Workbook wb = new XSSFWorkbook();
                Sheet sheet = wb.createSheet("Dream Informes");
                XSSFSheet sheet1 = (XSSFSheet) wb.createSheet("new sheet");
                Header header = sheet1.getFirstHeader();
                header.setCenter("Center First Page Header");
                Font font = wb.createFont();
                font.setFontHeightInPoints((short) 18);
                font.setFontName("Courier New");
                font.setItalic(true);
                CellStyle style = wb.createCellStyle();
                style.setFont(font);
                style.setFillBackgroundColor(IndexedColors.PLUM.getIndex());
                style.setFillPattern(FillPatternType.FINE_DOTS);

                style.setBorderBottom(BorderStyle.THIN);
                style.setBorderLeft(BorderStyle.THIN);
                style.setBorderRight(BorderStyle.THIN);
                style.setBorderBottom(BorderStyle.THIN);

                Row rowCol = sheet.createRow(0);
                for (int i = 0; i < tblDespachos.getColumnCount(); i++) {
                    Cell cell = rowCol.createCell(i);
                    cell.setCellValue(tblDespachos.getColumnName(i));
                    cell.setCellStyle(style);

                }

                for (int j = 0; j < tblDespachos.getRowCount(); j++) {
                    Row row = sheet.createRow(j + 1);
                    for (int k = 0; k < tblDespachos.getColumnCount(); k++) {
                        Cell cell = row.createCell(k);

                        if (tblDespachos.getValueAt(j, k) != null) {
                            cell.setCellValue(tblDespachos.getValueAt(j, k).toString());
                            style = wb.createCellStyle();
                            style.setFillForegroundColor(IndexedColors.ORANGE.getIndex());
                            style.setFillPattern(FillPatternType.SOLID_FOREGROUND);
                            style.setBorderBottom(BorderStyle.THIN);
                            style.setBorderLeft(BorderStyle.THIN);
                            style.setBorderRight(BorderStyle.THIN);
                            style.setBorderBottom(BorderStyle.THIN);

                            cell.setCellStyle(style);
                        }
                    }
                }
                FileOutputStream out = new FileOutputStream(new File(saveFile.toString()));
                wb.write(out);
                wb.close();
                out.close();
                openFile(saveFile.toString());
            } else {
                JOptionPane.showMessageDialog(null, "Error al generar archivo");
            }
        } catch (FileNotFoundException e) {
            System.out.println(e);
        } catch (IOException io) {
            System.out.println(io);
        }
    }//GEN-LAST:event_jButton2ActionPerformed

    
    public void openFile(String file) {
        try {
            File path = new File(file);
            Desktop.getDesktop().open(path);
        } catch (IOException ioe) {
            System.out.println(ioe);
        }
    }
    public void clear() {

    }
    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton BuscarInformeComuna;
    private com.toedter.calendar.JDateChooser InformeComunas1;
    private com.toedter.calendar.JDateChooser InformeComunas2;
    private javax.swing.JComboBox<String> cmbComuna;
    private javax.swing.JButton jButton2;
    private javax.swing.JLabel jLabel10;
    private javax.swing.JLabel jLabel11;
    private javax.swing.JLabel jLabel7;
    private javax.swing.JLabel jLabel8;
    private javax.swing.JLabel jLabel9;
    private javax.swing.JScrollPane jScrollPane2;
    private javax.swing.JTable tblDespachos;
    private javax.swing.JTextField txtTotal;
    // End of variables declaration//GEN-END:variables
}
