/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package clienteGUI;

import conexion.conexion;
import java.awt.Color;
import javax.swing.table.DefaultTableModel;
import java.awt.event.KeyAdapter;
import java.awt.event.KeyEvent;
import java.sql.Array;
import java.sql.PreparedStatement;
import java.sql.ResultSet;
import java.sql.SQLException;
import java.text.SimpleDateFormat;
import java.util.ArrayList;
import java.util.Date;
import java.util.logging.Level;
import java.util.logging.Logger;
import javax.swing.RowFilter;
import javax.swing.plaf.InternalFrameUI;
import javax.swing.plaf.basic.BasicInternalFrameUI;
import javax.swing.table.TableRowSorter;

/**
 *
 * @author danie
 */
public class VentaConfirmacion extends javax.swing.JInternalFrame {

    DefaultTableModel dtmBanco;
    TableRowSorter trs;
    DefaultTableModel modeloCarrito;
    int nroPedido = 0;
    conexion con = new conexion();

    public VentaConfirmacion() throws Exception {
        initComponents();
        bancos();
        this.getContentPane().setBackground(new Color(72, 70, 92));
       
        listarPendientes();

    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")

    private void listarPendientes() {
        
        modeloCarrito = new DefaultTableModel();

        modeloCarrito.addColumn("Nro Pedido");
        modeloCarrito.addColumn("Fecha Pedido");
        modeloCarrito.addColumn("Nombre Cliente");
        modeloCarrito.addColumn("Numero Telefono");
        modeloCarrito.addColumn("Monto");
        modeloCarrito.addColumn("Pack");
        this.tblPendientes.setModel(modeloCarrito);

        try {

            con.connections();
            PreparedStatement pstm = con.conexion.prepareStatement("select * from venta,cliente,pack where EST_ID_ESTADO  ='" + 1 + "' and"
                    + " venta.CLI_ID_CLIENTE=cliente.id_cliente and venta.PCK_ID_PACK=pack.id_pack ");
            ResultSet respuesta1 = pstm.executeQuery();

            while (respuesta1.next()) {

//                if (respuesta1.getInt("EST_ID_ESTADO") == 1) {

                    Object[] dato = {
                        respuesta1.getInt("vta_id_venta"),
                        respuesta1.getString("VTA_FECHA_ENTREGA"),
                        respuesta1.getString("cli_nombre")+" "+respuesta1.getString("cli_apellido"),
                        respuesta1.getString("cli_telefono"),
                        respuesta1.getString("vta_cantidad"),
                        respuesta1.getString("pack_nombre")};

                    modeloCarrito.addRow(dato);
//                }

            }

        } catch (Exception e) {
            System.out.println("no se listo pendientes por error : " + e);
        }

    }

    @Override
    public void setUI(InternalFrameUI ui) {
        super.setUI(ui);

        BasicInternalFrameUI frameUI = (BasicInternalFrameUI) getUI();
        if (frameUI != null) {
            frameUI.setNorthPane(null);
        }
    }


    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        txtBuscarBanco = new javax.swing.JTextField();
        jLabel6 = new javax.swing.JLabel();
        jLabel7 = new javax.swing.JLabel();
        jScrollPane2 = new javax.swing.JScrollPane();
        tblPendientes = new javax.swing.JTable();
        jPanel1 = new javax.swing.JPanel();
        jLabel1 = new javax.swing.JLabel();
        txtNroPedido = new javax.swing.JTextField();
        jLabel2 = new javax.swing.JLabel();
        txtCRut = new javax.swing.JTextField();
        jLabel3 = new javax.swing.JLabel();
        txtNCliente = new javax.swing.JTextField();
        JPago = new com.toedter.calendar.JDateChooser();
        jLabel4 = new javax.swing.JLabel();
        jLabel5 = new javax.swing.JLabel();
        cmbBancos = new javax.swing.JComboBox<>();
        jLabel9 = new javax.swing.JLabel();
        txtCodTransaccion = new javax.swing.JTextField();
        btnGuardarArticulo = new javax.swing.JButton();
        btnCancelarArticulo = new javax.swing.JButton();
        jButton1 = new javax.swing.JButton();
        jLabel8 = new javax.swing.JLabel();

        setBackground(new java.awt.Color(102, 102, 255));
        setBorder(javax.swing.BorderFactory.createMatteBorder(3, 3, 3, 3, new java.awt.Color(0, 0, 0)));
        setAutoscrolls(true);
        setCursor(new java.awt.Cursor(java.awt.Cursor.DEFAULT_CURSOR));
        setEnabled(false);
        setFocusCycleRoot(false);
        setFocusable(false);
        setPreferredSize(new java.awt.Dimension(1006, 611));
        setRequestFocusEnabled(false);
        setVerifyInputWhenFocusTarget(false);
        setVisible(true);

        txtBuscarBanco.setFont(new java.awt.Font("Tahoma", 0, 14)); // NOI18N
        txtBuscarBanco.setText("buscar pedido....");
        txtBuscarBanco.addFocusListener(new java.awt.event.FocusAdapter() {
            public void focusGained(java.awt.event.FocusEvent evt) {
                txtBuscarBancoFocusGained(evt);
            }
        });
        txtBuscarBanco.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyTyped(java.awt.event.KeyEvent evt) {
                txtBuscarBancoKeyTyped(evt);
            }
        });

        jLabel6.setIcon(new javax.swing.ImageIcon(getClass().getResource("/recurso/icons/buscar.png"))); // NOI18N

        jLabel7.setFont(new java.awt.Font("Verdana", 1, 18)); // NOI18N
        jLabel7.setForeground(new java.awt.Color(255, 255, 255));
        jLabel7.setText("Ventas Pendientes de Pago");

        tblPendientes.setBorder(new javax.swing.border.SoftBevelBorder(javax.swing.border.BevelBorder.RAISED));
        tblPendientes.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null}
            },
            new String [] {
                "Title 1", "Title 2", "Title 3", "Title 4"
            }
        ));
        tblPendientes.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                tblPendientesMouseClicked(evt);
            }
        });
        jScrollPane2.setViewportView(tblPendientes);

        jPanel1.setBackground(new java.awt.Color(72, 70, 92));
        jPanel1.setBorder(new javax.swing.border.SoftBevelBorder(javax.swing.border.BevelBorder.RAISED));
        jPanel1.setForeground(new java.awt.Color(255, 255, 255));

        jLabel1.setFont(new java.awt.Font("Tahoma", 1, 18)); // NOI18N
        jLabel1.setForeground(new java.awt.Color(255, 255, 255));
        jLabel1.setText("Nro Pedido");

        txtNroPedido.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                txtNroPedidoActionPerformed(evt);
            }
        });

        jLabel2.setFont(new java.awt.Font("Tahoma", 1, 18)); // NOI18N
        jLabel2.setForeground(new java.awt.Color(255, 255, 255));
        jLabel2.setText("Rut");

        jLabel3.setFont(new java.awt.Font("Tahoma", 1, 18)); // NOI18N
        jLabel3.setForeground(new java.awt.Color(255, 255, 255));
        jLabel3.setText("Nombre Cliente");

        jLabel4.setFont(new java.awt.Font("Tahoma", 1, 18)); // NOI18N
        jLabel4.setForeground(new java.awt.Color(255, 255, 255));
        jLabel4.setText("Fecha Pago");

        jLabel5.setFont(new java.awt.Font("Tahoma", 1, 18)); // NOI18N
        jLabel5.setForeground(new java.awt.Color(255, 255, 255));
        jLabel5.setText("Banco");

        cmbBancos.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "Seleccione banco" }));

        jLabel9.setFont(new java.awt.Font("Tahoma", 1, 18)); // NOI18N
        jLabel9.setForeground(new java.awt.Color(255, 255, 255));
        jLabel9.setText("Codigo Transaccion");

        btnGuardarArticulo.setIcon(new javax.swing.ImageIcon(getClass().getResource("/recurso/icons/cheque.png"))); // NOI18N
        btnGuardarArticulo.setText("Confirmar");
        btnGuardarArticulo.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnGuardarArticuloActionPerformed(evt);
            }
        });

        btnCancelarArticulo.setIcon(new javax.swing.ImageIcon(getClass().getResource("/recurso/icons/cancelar.png"))); // NOI18N
        btnCancelarArticulo.setText("Cancelar");
        btnCancelarArticulo.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnCancelarArticuloActionPerformed(evt);
            }
        });

        jButton1.setIcon(new javax.swing.ImageIcon(getClass().getResource("/recurso/icons/buscar.png"))); // NOI18N
        jButton1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton1ActionPerformed(evt);
            }
        });

        jLabel8.setFont(new java.awt.Font("Tahoma", 1, 24)); // NOI18N
        jLabel8.setForeground(new java.awt.Color(255, 255, 255));
        jLabel8.setText("Validacion de pagos");

        javax.swing.GroupLayout jPanel1Layout = new javax.swing.GroupLayout(jPanel1);
        jPanel1.setLayout(jPanel1Layout);
        jPanel1Layout.setHorizontalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                        .addGroup(jPanel1Layout.createSequentialGroup()
                            .addComponent(btnCancelarArticulo)
                            .addGap(48, 48, 48)
                            .addComponent(btnGuardarArticulo))
                        .addGroup(jPanel1Layout.createSequentialGroup()
                            .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                                .addGroup(jPanel1Layout.createSequentialGroup()
                                    .addComponent(jLabel1)
                                    .addGap(18, 18, 18)
                                    .addComponent(txtNroPedido, javax.swing.GroupLayout.PREFERRED_SIZE, 192, javax.swing.GroupLayout.PREFERRED_SIZE))
                                .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel1Layout.createSequentialGroup()
                                    .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                        .addComponent(jLabel2)
                                        .addComponent(jLabel5))
                                    .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                    .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                                        .addComponent(txtCRut)
                                        .addComponent(cmbBancos, 0, 192, Short.MAX_VALUE))))
                            .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                            .addComponent(jButton1, javax.swing.GroupLayout.PREFERRED_SIZE, 33, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addGap(60, 60, 60)
                            .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                .addGroup(jPanel1Layout.createSequentialGroup()
                                    .addComponent(jLabel9)
                                    .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                    .addComponent(txtCodTransaccion))
                                .addGroup(jPanel1Layout.createSequentialGroup()
                                    .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                        .addComponent(jLabel3)
                                        .addComponent(jLabel4))
                                    .addGap(42, 42, 42)
                                    .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                                        .addComponent(txtNCliente)
                                        .addComponent(JPago, javax.swing.GroupLayout.DEFAULT_SIZE, 228, Short.MAX_VALUE))))))
                    .addComponent(jLabel8))
                .addGap(78, 78, 78))
        );
        jPanel1Layout.setVerticalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addComponent(jLabel8)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                    .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                        .addComponent(txtNroPedido, javax.swing.GroupLayout.PREFERRED_SIZE, 24, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGroup(javax.swing.GroupLayout.Alignment.LEADING, jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(jLabel1)
                            .addComponent(jLabel3)
                            .addComponent(txtNCliente, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)))
                    .addComponent(jButton1, javax.swing.GroupLayout.PREFERRED_SIZE, 35, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(29, 29, 29)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                    .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                        .addComponent(jLabel2)
                        .addComponent(txtCRut, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addComponent(jLabel4))
                    .addComponent(JPago, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(26, 26, 26)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel5)
                    .addComponent(cmbBancos, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabel9)
                    .addComponent(txtCodTransaccion, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(18, 18, 18)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(btnCancelarArticulo)
                    .addComponent(btnGuardarArticulo))
                .addContainerGap())
        );

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGap(38, 38, 38)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                    .addComponent(jPanel1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                        .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                            .addComponent(jLabel7, javax.swing.GroupLayout.PREFERRED_SIZE, 331, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 280, Short.MAX_VALUE)
                            .addComponent(txtBuscarBanco, javax.swing.GroupLayout.PREFERRED_SIZE, 267, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                            .addComponent(jLabel6))
                        .addComponent(jScrollPane2)))
                .addContainerGap(47, Short.MAX_VALUE))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jPanel1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jLabel7)
                    .addComponent(txtBuscarBanco, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabel6, javax.swing.GroupLayout.PREFERRED_SIZE, 30, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jScrollPane2, javax.swing.GroupLayout.PREFERRED_SIZE, 128, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(45, Short.MAX_VALUE))
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void txtBuscarBancoKeyTyped(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_txtBuscarBancoKeyTyped
        txtBuscarBanco.addKeyListener(new KeyAdapter() {
            @Override
            public void keyReleased(KeyEvent ke) {
                trs.setRowFilter(RowFilter.regexFilter("(?i)" + txtBuscarBanco.getText(), 0));
            }

        });
        trs = new TableRowSorter(dtmBanco);
        tblPendientes.setRowSorter(trs);
        if (txtBuscarBanco.getText().equals("")) {
            try {
                listarPendientes();
            } catch (Exception ex) {
                Logger.getLogger(VentaConfirmacion.class.getName()).log(Level.SEVERE, null, ex);
            }
        }
    }//GEN-LAST:event_txtBuscarBancoKeyTyped

    private void btnGuardarArticuloActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnGuardarArticuloActionPerformed

        String formato = JPago.getDateFormatString();
        Date date = JPago.getDate();
        SimpleDateFormat sdf = new SimpleDateFormat("yyyy/MM/dd");
        String fechaEntrega = (String.valueOf(sdf.format(date)));
        listarPendientes();

        try {

            con.connections();
            String sql = String.format("update venta set VTA_FECHA_TRANSFERENCIA='%s', BAN_ID_BANCO='%s', VTA_CODIGO_TRANSFERENCIA='%s',EST_ID_ESTADO=%s where venta.VTA_ID_VENTA='%s'"
                    + "", fechaEntrega, cmbBancos.getSelectedIndex(), String.valueOf(txtCodTransaccion.getText()), 2, String.valueOf(txtNroPedido.getText()));

            PreparedStatement respuesta = con.conexion.prepareStatement(sql);

//            System.out.println(fechaEntrega);
//            System.out.println( cmbBancos.getSelectedIndex());
//            System.out.println(String.valueOf(txtCodTransaccion.getText()));
//            System.out.println(String.valueOf(txtNroPedido.getText()));
//
//            respuesta.setString(1, fechaEntrega);
//            respuesta.setInt(2, cmbBancos.getSelectedIndex());
//            respuesta.setString(3, String.valueOf(txtCodTransaccion.getText()));
//            respuesta.setInt(4, 2);
//            respuesta.setString(5,String.valueOf(txtNroPedido.getText()));
            respuesta.execute();

            System.out.println("update ejecutado");
            modeloCarrito.setRowCount(0);
            
            listarPendientes();

            con.cerrar();
            clear();
           

        } catch (SQLException e) {
            System.out.println(e);
            System.out.println("update no ejecutado");
        }
        
         
        


    }//GEN-LAST:event_btnGuardarArticuloActionPerformed

    private void btnCancelarArticuloActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnCancelarArticuloActionPerformed
        clear();
    }//GEN-LAST:event_btnCancelarArticuloActionPerformed

    private void txtNroPedidoActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_txtNroPedidoActionPerformed


    }//GEN-LAST:event_txtNroPedidoActionPerformed

    private void tblPendientesMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_tblPendientesMouseClicked
        int fila = tblPendientes.getSelectedRow();
        nroPedido = ((int) tblPendientes.getValueAt(fila, 0));
        txtNroPedido.setText(String.valueOf(nroPedido));
        System.out.println("captura de id ok : " + nroPedido);
    }//GEN-LAST:event_tblPendientesMouseClicked

    private void jButton1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton1ActionPerformed

        System.out.println(nroPedido);
        buscarId(nroPedido);


    }//GEN-LAST:event_jButton1ActionPerformed

    private void txtBuscarBancoFocusGained(java.awt.event.FocusEvent evt) {//GEN-FIRST:event_txtBuscarBancoFocusGained
        txtBuscarBanco.setText("");
    }//GEN-LAST:event_txtBuscarBancoFocusGained

    public void buscarId(int id) {

        int contador = 0;

        try {

            con.connections();
            PreparedStatement pstm = con.conexion.prepareStatement("select * from venta,cliente where venta.VTA_ID_VENTA ='" + id + "' AND "
                    + "venta.CLI_ID_CLIENTE=cliente.id_cliente");
            ResultSet respuesta1 = pstm.executeQuery();

            while (respuesta1.next()) {

                String nombre = respuesta1.getString("cli_nombre");
                String apellido = respuesta1.getString("cli_apellido");
                String rut = respuesta1.getString("cli_rut");

                txtNCliente.setText(nombre + " " + apellido);
                txtCRut.setText(rut);

                System.out.println("se deberian haber cargado los input");
                contador++;

            }

            con.cerrar();

        } catch (Exception e) {

            System.out.println("no paso nah, error : " + e);

        }

    }

    void bancos() {

        try {
            con.connections();
            PreparedStatement pstm = con.conexion.prepareStatement("select * from bancos");
            ResultSet respuesta = pstm.executeQuery();

            while (respuesta.next()) {

                cmbBancos.addItem(respuesta.getString("ban_descripcion"));
            }

        } catch (SQLException e) {

        }

    }

    public void clear() {
        
        
        txtNroPedido.setText("");
        txtCRut.setText("");
        txtCodTransaccion.setText("");
        txtNCliente.setText("");
        txtCodTransaccion.setText("");
        cmbBancos.setSelectedIndex(0);
        

    }
    // Variables declaration - do not modify//GEN-BEGIN:variables
    private com.toedter.calendar.JDateChooser JPago;
    private javax.swing.JButton btnCancelarArticulo;
    private javax.swing.JButton btnGuardarArticulo;
    private javax.swing.JComboBox<String> cmbBancos;
    private javax.swing.JButton jButton1;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JLabel jLabel6;
    private javax.swing.JLabel jLabel7;
    private javax.swing.JLabel jLabel8;
    private javax.swing.JLabel jLabel9;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JScrollPane jScrollPane2;
    private javax.swing.JTable tblPendientes;
    private javax.swing.JTextField txtBuscarBanco;
    private javax.swing.JTextField txtCRut;
    private javax.swing.JTextField txtCodTransaccion;
    private javax.swing.JTextField txtNCliente;
    private javax.swing.JTextField txtNroPedido;
    // End of variables declaration//GEN-END:variables
}
