/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package clienteGUI;

import conexion.conexion;
import java.awt.Color;
import javax.swing.table.DefaultTableModel;
import java.sql.PreparedStatement;
import java.sql.ResultSet;
import java.sql.SQLException;
import java.text.SimpleDateFormat;
import java.util.Date;
import javax.swing.plaf.InternalFrameUI;
import javax.swing.plaf.basic.BasicInternalFrameUI;
import javax.swing.table.TableRowSorter;

/**
 *
 * @author danie
 */
public class VentaDespachosPorDia extends javax.swing.JInternalFrame {

    DefaultTableModel dtmBanco;
    TableRowSorter trs;
    DefaultTableModel modeloDespachos;
    int nroPedido = 0;
    conexion con = new conexion();

    public VentaDespachosPorDia() throws Exception {
        initComponents();

        this.getContentPane().setBackground(new Color(72, 70, 92));
        modeloDespachos = new DefaultTableModel();
        modeloDespachos.addColumn("Nro Pedido");
        modeloDespachos.addColumn("Pack");
        modeloDespachos.addColumn("Destinatario");
        modeloDespachos.addColumn("Fecha entrega");
        modeloDespachos.addColumn("Comuna");
        modeloDespachos.addColumn("Direccion");
        modeloDespachos.addColumn("Hora entrega");
        this.tblDespachos.setModel(modeloDespachos);

    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")

    private void listarPendientes() {

        try {

            con.connections();
            PreparedStatement pstm = con.conexion.prepareStatement("select * from venta,cliente,pack where EST_ID_ESTADO  ='" + 1 + "' and"
                    + " venta.CLI_ID_CLIENTE=cliente.id_cliente and venta.PCK_ID_PACK=pack.id_pack ");
            ResultSet respuesta1 = pstm.executeQuery();

            while (respuesta1.next()) {

//                if (respuesta1.getInt("EST_ID_ESTADO") == 1) {
                Object[] dato = {
                    respuesta1.getInt("vta_id_venta"),
                    respuesta1.getString("VTA_FECHA_ENTREGA"),
                    respuesta1.getString("cli_nombre")+" "+respuesta1.getString("cli_apellido"),
                    respuesta1.getString("cli_telefono"),
                    respuesta1.getString("VTA_TOTAL"),
                    respuesta1.getString("pack_nombre")};

                modeloDespachos.addRow(dato);
//                }

            }

        } catch (Exception e) {
            System.out.println("no se listo pendientes por error : " + e);
        }

    }

    @Override
    public void setUI(InternalFrameUI ui) {
        super.setUI(ui);

        BasicInternalFrameUI frameUI = (BasicInternalFrameUI) getUI();
        if (frameUI != null) {
            frameUI.setNorthPane(null);
        }
    }


    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jLabel7 = new javax.swing.JLabel();
        jScrollPane2 = new javax.swing.JScrollPane();
        tblDespachos = new javax.swing.JTable();
        JdateDespachos = new com.toedter.calendar.JDateChooser();
        jButton1 = new javax.swing.JButton();

        setBackground(new java.awt.Color(102, 102, 255));
        setBorder(javax.swing.BorderFactory.createMatteBorder(3, 3, 3, 3, new java.awt.Color(0, 0, 0)));
        setAutoscrolls(true);
        setCursor(new java.awt.Cursor(java.awt.Cursor.DEFAULT_CURSOR));
        setEnabled(false);
        setFocusCycleRoot(false);
        setFocusable(false);
        setPreferredSize(new java.awt.Dimension(1006, 611));
        setRequestFocusEnabled(false);
        setVerifyInputWhenFocusTarget(false);
        setVisible(true);

        jLabel7.setFont(new java.awt.Font("Verdana", 1, 18)); // NOI18N
        jLabel7.setForeground(new java.awt.Color(255, 255, 255));
        jLabel7.setText("Ventas Pendientes de Pago");

        tblDespachos.setBorder(new javax.swing.border.SoftBevelBorder(javax.swing.border.BevelBorder.RAISED));
        tblDespachos.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null}
            },
            new String [] {
                "Title 1", "Title 2", "Title 3", "Title 4"
            }
        ));
        tblDespachos.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                tblDespachosMouseClicked(evt);
            }
        });
        jScrollPane2.setViewportView(tblDespachos);

        JdateDespachos.setFocusable(false);
        JdateDespachos.addContainerListener(new java.awt.event.ContainerAdapter() {
            public void componentRemoved(java.awt.event.ContainerEvent evt) {
                JdateDespachosComponentRemoved(evt);
            }
        });
        JdateDespachos.addFocusListener(new java.awt.event.FocusAdapter() {
            public void focusLost(java.awt.event.FocusEvent evt) {
                JdateDespachosFocusLost(evt);
            }
        });

        jButton1.setText("OK");
        jButton1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton1ActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGap(35, 35, 35)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING, false)
                    .addGroup(layout.createSequentialGroup()
                        .addComponent(jLabel7, javax.swing.GroupLayout.PREFERRED_SIZE, 331, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                        .addComponent(JdateDespachos, javax.swing.GroupLayout.PREFERRED_SIZE, 215, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(18, 18, 18)
                        .addComponent(jButton1, javax.swing.GroupLayout.PREFERRED_SIZE, 67, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addComponent(jScrollPane2, javax.swing.GroupLayout.PREFERRED_SIZE, 915, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addContainerGap(50, Short.MAX_VALUE))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addGap(39, 39, 39)
                        .addComponent(jLabel7))
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                        .addGap(32, 32, 32)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                            .addComponent(JdateDespachos, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                            .addComponent(jButton1, javax.swing.GroupLayout.DEFAULT_SIZE, 30, Short.MAX_VALUE))))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jScrollPane2, javax.swing.GroupLayout.PREFERRED_SIZE, 305, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(201, Short.MAX_VALUE))
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void tblDespachosMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_tblDespachosMouseClicked

    }//GEN-LAST:event_tblDespachosMouseClicked

    private void JdateDespachosFocusLost(java.awt.event.FocusEvent evt) {//GEN-FIRST:event_JdateDespachosFocusLost

        
    }//GEN-LAST:event_JdateDespachosFocusLost

    private void jButton1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton1ActionPerformed
        
        modeloDespachos.setRowCount(0);
        
        Date date = JdateDespachos.getDate();
        SimpleDateFormat sdf = new SimpleDateFormat("yyyy/MM/dd");
        String fechaDespacho = (String.valueOf(sdf.format(date)));
        
        System.out.println(fechaDespacho);
        
        System.out.println("hola despachos");

        try {

            con.connections();
            PreparedStatement pstm = con.conexion.prepareStatement("select * from venta,cliente,pack,comuna where VTA_FECHA_ENTREGA='" + fechaDespacho + "' and"
                    + " venta.CLI_ID_CLIENTE=cliente.id_cliente and venta.PCK_ID_PACK=pack.id_pack AND venta.COM_ID_COMUNA=comuna.id_comuna");
            ResultSet respuesta1 = pstm.executeQuery();

            while (respuesta1.next()) {

//                if (respuesta1.getInt("EST_ID_ESTADO") == 1) {
                Object[] dato = {
                    respuesta1.getInt("vta_id_venta"),
                    respuesta1.getString("pack_nombre"),
                    respuesta1.getString("VTA_NOMBRE_DESTINATARIO")+" "+respuesta1.getString("VTA_APELLIDO_DESTINATARIO"),
                    respuesta1.getString("VTA_FECHA_ENTREGA"),                   
                    respuesta1.getString("com_nombre"),
                    respuesta1.getString("VTA_DIRECCION_DESTINATARIO"),
                    respuesta1.getString("VTA_HORA_ENTREGA_INICIAL")+" - "+respuesta1.getString("VTA_HORA_ENTREGA_FINAL")};

                modeloDespachos.addRow(dato);
//                }

            }

        } catch (Exception e) {
            System.out.println("no se listo pendientes por error : " + e);
        }
    }//GEN-LAST:event_jButton1ActionPerformed

    private void JdateDespachosComponentRemoved(java.awt.event.ContainerEvent evt) {//GEN-FIRST:event_JdateDespachosComponentRemoved
        try {

            con.connections();
            PreparedStatement pstm = con.conexion.prepareStatement("select * from venta,cliente,pack,comuna where  "
                    + " venta.CLI_ID_CLIENTE=cliente.id_cliente and venta.PCK_ID_PACK=pack.id_pack AND venta.COM_ID_COMUNA=comuna.id_comuna");
            ResultSet respuesta1 = pstm.executeQuery();

            while (respuesta1.next()) {

//                if (respuesta1.getInt("EST_ID_ESTADO") == 1) {
                Object[] dato = {
                    respuesta1.getInt("vta_id_venta"),
                    respuesta1.getString("pack_nombre"),
                    respuesta1.getString("VTA_NOMBRE_DESTINATARIO"),
                    respuesta1.getString("VTA_FECHA_ENTREGA"),                   
                    respuesta1.getString("com_nombre"),
                    respuesta1.getString("VTA_DIRECCION_DESTINATARIO"),
                    respuesta1.getString("VTA_HORA_ENTREGA_INICIAL")};

                modeloDespachos.addRow(dato);
//                }

            }

        } catch (Exception e) {
            System.out.println("no se listo pendientes por error : " + e);
        }
    }//GEN-LAST:event_JdateDespachosComponentRemoved

    public void clear() {

    }
    // Variables declaration - do not modify//GEN-BEGIN:variables
    private com.toedter.calendar.JDateChooser JdateDespachos;
    private javax.swing.JButton jButton1;
    private javax.swing.JLabel jLabel7;
    private javax.swing.JScrollPane jScrollPane2;
    private javax.swing.JTable tblDespachos;
    // End of variables declaration//GEN-END:variables
}
